@startyaml
Resources:
  PhotosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Photos
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: "S"
        - AttributeName: "photoId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "username"
          KeyType: "HASH"
        - AttributeName: "photoId"
          KeyType: "RANGE"
      BillingMode: "PAY_PER_REQUEST
@endyaml